export const CARS = [
  {
    id: 1,
    name: 'Porsche 911 Turbo S',
    brand: 'Porsche',
    category: 'sport',
    image: 'https://www.goodwood.com/globalassets/.road--racing/road/news/2020/3-march/porsche-911-turbo/porsche-911-turbo-s-2020-goodwood-03032020.jpg?rxy=0.5,0.5',
    powerHp: 650,
    zeroToHundred: 2.7,
    drivetrain: 'AWD',
    description: 'Ikonikus sportautó, turbós boxer motorral és lélegzetelállító teljesítménnyel.',
  },
  {
    id: 2,
    name: 'Ferrari 488 GTB',
    brand: 'Ferrari',
    category: 'sport',
    image: 'https://static01.nyt.com/images/2016/08/05/automobiles/autoreviews/driven-ferrari-488gtb/driven-ferrari-488gtb-superJumbo.jpg',
    powerHp: 670,
    zeroToHundred: 3.0,
    drivetrain: 'RWD',
    description: 'Középmotoros Ferrari, kivételes vezethetőséggel és lenyűgöző V8 hanggal.',
  },
  {
    id: 3,
    name: 'BMW M4 Competition',
    brand: 'BMW',
    category: 'sport',
    image: 'https://blog.consumerguide.com/wp-content/uploads/sites/2/2021/09/aIMG_5370.jpg',
    powerHp: 510,
    zeroToHundred: 3.9,
    drivetrain: 'RWD',
    description: 'Erős turbómotor, precíz futómű és agresszív megjelenés.',
  },
  {
    id: 4,
    name: 'Mercedes-AMG GT R',
    brand: 'Mercedes',
    category: 'sport',
    image: 'https://cloud.leparking.fr/2021/01/26/13/13/mercedes-amg-gt-mercedes-benz-amg-gts-edition-1-peinture-designo-solarbeam-yellow-tva-recuperable-jaune_7952856614.jpg',
    powerHp: 585,
    zeroToHundred: 3.6,
    drivetrain: 'RWD',
    description: 'AMG V8 Biturbo motorral szerelt versenypályára született sportautó.',
  },
  {
    id: 5,
    name: 'Mustang Shelby GT500',
    brand: 'Mustang',
    category: 'sport',
    image: 'https://fordauthority.com/wp-content/uploads/2024/02/2022-Ford-Mustang-Shelby-GT500-Heritage-Auction-Exterior-001-Front-Three-Quarters-850x567.jpg',
    powerHp: 760,
    zeroToHundred: 3.4,
    drivetrain: 'RWD',
    description: 'Amerikai izomautó brutális teljesítménnyel és jellegzetes V8 hanggal.',
  },
  {
    id: 6,
    name: 'Ferrari F8 Tributo',
    brand: 'Ferrari',
    category: 'sport',
    image: 'https://www.topgear.com/sites/default/files/cars-car/image/2019/09/tg_-_ferrari_f8_tributo_-091.jpg',
    powerHp: 720,
    zeroToHundred: 2.9,
    drivetrain: 'RWD',
    description: 'Kiemelkedő aerodinamika és lélegzetelállító olasz dizájn.',
  },

  // SUV (6)
  {
    id: 7,
    name: 'BMW X5 M Competition',
    brand: 'BMW',
    category: 'suv',
    image: 'https://hips.hearstapps.com/hmg-prod/images/p90495464-1677001974.jpg?crop=0.720xw:0.608xh;0.250xw,0.329xh&resize=2048:*',
    powerHp: 625,
    zeroToHundred: 3.8,
    drivetrain: 'AWD',
    description: 'Nagy teljesítményű prémium SUV, sportos futóművel és luxusszintű kényelemmel.',
  },
  {
    id: 8,
    name: 'Mercedes-AMG GLE 63 S',
    brand: 'Mercedes',
    category: 'suv',
    image: 'https://gtspirit.com/wp-content/uploads/2020/02/20C0059_023.jpg',
    powerHp: 612,
    zeroToHundred: 3.8,
    drivetrain: 'AWD',
    description: 'Erős AMG SUV sportos megjelenéssel és bivalyerős V8 motorral.',
  },
  {
    id: 9,
    name: 'Porsche Cayenne Turbo GT',
    brand: 'Porsche',
    category: 'suv',
    image: 'https://newsroom.porsche.com/.imaging/mte/porsche-templating-theme/image_1290x726/dam/pnr/2024/Products/The-new-Cayenne-GTS/Porsche_Kroatien_GTS_DSF4413_Gruppe_V03.jpg/jcr:content/Porsche_Kroatien_GTS_DSF4413_Gruppe_V03.jpg',
    powerHp: 640,
    zeroToHundred: 3.3,
    drivetrain: 'AWD',
    description: 'A Cayenne leggyorsabb változata, hihetetlen dinamika és precizitás.',
  },
  {
    id: 10,
    name: 'BMW X6 M',
    brand: 'BMW',
    category: 'suv',
    image: 'https://www.bmw-m.com/content/dam/bmw/marketBMW_M/www_bmw-m_com/all-models/m-automobile/x6m/2023/bmw-x6-m-competition-individual-ai-01.png',
    powerHp: 600,
    zeroToHundred: 3.9,
    drivetrain: 'AWD',
    description: 'Kupé-SUV kategória egyik legerősebb tagja, elegáns és agresszív forma.',
  },
  {
    id: 11,
    name: 'Mercedes G-Class AMG G63',
    brand: 'Mercedes',
    category: 'suv',
    image: 'https://www.topgear.com/sites/default/files/2024/11/1-Mercedes-AMG-G63-review-UK-2024.jpg',
    powerHp: 585,
    zeroToHundred: 4.5,
    drivetrain: 'AWD',
    description: 'Legendás terepjáró luxuskivitelben, jellegzetes AMG hanggal.',
  },
  {
    id: 12,
    name: 'Mustang Mach-E GT',
    brand: 'Mustang',
    category: 'suv',
    image: 'https://cdn.motor1.com/images/mgl/RP4Am/s3/mustang-mach-e-gt-performance-edition-three-quarters.jpg',
    powerHp: 480,
    zeroToHundred: 3.7,
    drivetrain: 'AWD',
    description: 'Teljesen elektromos Mustang SUV, modern technológiával és sportos karakterrel.',
  },

  // ELEKTROMOS (6)
  {
    id: 13,
    name: 'Tesla Model S Plaid',
    brand: 'Tesla',
    category: 'ev',
    image: 'https://media.autoexpress.co.uk/image/private/s--X-WVjvBW--/f_auto,t_content-image-full-desktop@1/v1688744557/autoexpress/2023/07/Tesla%20Model%20S%20Plaid%202023%20UK.jpg',
    powerHp: 1020,
    zeroToHundred: 2.1,
    drivetrain: 'AWD',
    description: 'Az egyik leggyorsabb elektromos autó a világon.',
  },
  {
    id: 14,
    name: 'Tesla Model 3 Performance',
    brand: 'Tesla',
    category: 'ev',
    image: 'https://media.drive.com.au/obj/tx_q:50,rs:auto:1920:1080:1/driveau/upload/cms/uploads/mqmgootc29mdg04wctih',
    powerHp: 460,
    zeroToHundred: 3.3,
    drivetrain: 'AWD',
    description: 'Letisztult dizájn, brutális gyorsulás, tökéletes napi használatra.',
  },
  {
    id: 15,
    name: 'Porsche Taycan Turbo S',
    brand: 'Porsche',
    category: 'ev',
    image: 'https://www.ar-cars.cz/cache/images/project/010/10003/1920x1094-exact/default/55/13655-porsche-taycan-turbo-s-keramiky-pano-hud-0.jpeg',
    powerHp: 761,
    zeroToHundred: 2.8,
    drivetrain: 'AWD',
    description: 'Az egyik legjobb elektromos sportautó, prémium élménnyel.',
  },
  {
    id: 16,
    name: 'Mercedes EQS 580',
    brand: 'Mercedes',
    category: 'ev',
    image: 'https://ev-database.org/img/auto/Mercedes_EQS_2021/Mercedes_EQS_2021-01.jpg',
    powerHp: 523,
    zeroToHundred: 4.3,
    drivetrain: 'AWD',
    description: 'Luxus elektromos limuzin, futurisztikus technológiai csomaggal.',
  },
  {
    id: 17,
    name: 'BMW i4 M50',
    brand: 'BMW',
    category: 'ev',
    image: 'https://www.autoaddikt.hu/kepek/bmw-i4-m50-teszt-autoaddikt-45.jpg',
    powerHp: 544,
    zeroToHundred: 3.9,
    drivetrain: 'AWD',
    description: 'Sportos elektromos BMW, kiváló hatótávval és teljesítménnyel.',
  },
  {
    id: 18,
    name: 'Ford Mustang Mach-E',
    brand: 'Mustang',
    category: 'ev',
    image: 'https://cka-dash.s3.amazonaws.com/073-0923-FOC23163/mainimage.jpg',
    powerHp: 346,
    zeroToHundred: 5.1,
    drivetrain: 'AWD',
    description: 'Elektromos Mustang, modern dizájn és praktikum.',
  },

  // KLASSZIKUS (6)
  {
    id: 19,
    name: 'Ferrari Testarossa (1984)',
    brand: 'Ferrari',
    category: 'classic',
    image: 'https://maji97.com/wp-content/uploads/2024/03/otr07154-%E2%80%94-krupnyj-razmer.jpeg',
    powerHp: 390,
    zeroToHundred: 5.8,
    drivetrain: 'RWD',
    description: 'Ikonikus Ferrari a 80-as évekből, jellegzetes oldalsó légbeömlőkkel.',
  },
  {
    id: 20,
    name: 'Porsche 911 Carrera (1980)',
    brand: 'Porsche',
    category: 'classic',
    image: 'https://images.classic.com/vehicles/001236d3a9c58046cbc38ea17811ec637d1bf030.jpg?ar=16%3A9&fit=crop&h=338&w=600',
    powerHp: 204,
    zeroToHundred: 6.5,
    drivetrain: 'RWD',
    description: 'Klasszikus 911, léghűtéses boxermotorral.',
  },
  {
    id: 21,
    name: 'Ford Mustang Fastback (1967)',
    brand: 'Mustang',
    category: 'classic',
    image: 'https://www.topgear.com/sites/default/files/2024/08/413A1291.jpg',
    powerHp: 271,
    zeroToHundred: 6.8,
    drivetrain: 'RWD',
    description: 'Az egyik legismertebb amerikai klasszikus izomautó.',
  },
  {
    id: 22,
    name: 'Mercedes SL 300 Gullwing',
    brand: 'Mercedes',
    category: 'classic',
    image: 'https://images.hgmsites.net/hug/1955-mercedes-benz-300-sl-alloy-gullwing--photo-credit-rm-sothebys_100828272_h.jpg',
    powerHp: 215,
    zeroToHundred: 8.8,
    drivetrain: 'RWD',
    description: 'A híres „sirályszárnyas” Mercedes, amely máig gyűjtői álom.',
  },
  {
    id: 23,
    name: 'BMW E30 M3',
    brand: 'BMW',
    category: 'classic',
    image: 'https://racemarket.net/oc-content/uploads/46/67840.jpg',
    powerHp: 200,
    zeroToHundred: 6.7,
    drivetrain: 'RWD',
    description: 'A DTM legenda utcai változata, örök kedvenc.',
  },
  {
    id: 24,
    name: 'Ferrari Dino 246 GT',
    brand: 'Ferrari',
    category: 'classic',
    image: 'https://www.amalgamcollection.com/cdn/shop/articles/M5751-SPI-ERO-BES-SN12_website_photos_1_1024x1024.jpg?v=1656090700',
    powerHp: 195,
    zeroToHundred: 7.0,
    drivetrain: 'RWD',
    description: 'Gyűjtői Ferrari, klasszikus olasz eleganciával és könnyed vezethetőséggel.',
  },
];

export const CATEGORIES = [
  { key: 'all', label: 'Összes kategória' },
  { key: 'sport', label: 'Sport' },
  { key: 'suv', label: 'SUV' },
  { key: 'ev', label: 'Elektromos' },
  { key: 'classic', label: 'Klasszikus' },
  { key: 'favorites', label: 'Kedvencek' },
];

export const BRANDS = [
  { key: 'all', label: 'Összes márka' },
  { key: 'Porsche', label: 'Porsche' },
  { key: 'BMW', label: 'BMW' },
  { key: 'Mercedes', label: 'Mercedes' },
  { key: 'Tesla', label: 'Tesla' },
  { key: 'Mustang', label: 'Mustang' },
  { key: 'Ferrari', label: 'Ferrari' },
];